# Generated by Django 5.0.4 on 2024-05-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="retirada",
            old_name="data_devolução",
            new_name="data_devolucao",
        ),
    ]
