# Generated by Django 5.0.4 on 2024-05-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_rename_data_devolução_retirada_data_devolucao"),
    ]

    operations = [
        migrations.AddField(
            model_name="retirada",
            name="quantidade",
            field=models.PositiveIntegerField(null=int),
            preserve_default=int,
        ),
    ]
